# Generated by Django 6.0 on 2025-12-22 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address for the waitlist', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('date_signed_up', models.DateTimeField(auto_now_add=True, help_text='Date and time when the user signed up')),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-date_signed_up'],
            },
        ),
    ]
