# Generated by Django 6.0 on 2025-12-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='what_mostly_share',
            field=models.CharField(blank=True, choices=[('ideas', 'Ideas'), ('research', 'Research'), ('summaries', 'Summaries'), ('notes', 'Notes')], help_text='What do you mostly share?', max_length=20, null=True),
        ),
    ]
