# Generated by Django 6.0 on 2025-12-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_waitlist_what_mostly_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(help_text='Date of the visit', unique=True)),
                ('visit_count', models.IntegerField(default=0, help_text='Number of visits on this date')),
                ('last_visit', models.DateTimeField(auto_now=True, help_text='Last time a visit was recorded')),
            ],
            options={
                'verbose_name': 'Page Visit',
                'verbose_name_plural': 'Page Visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
